export const SITE_TITLE = 'Sui dApp Starter'
export const SITE_SLOGAN = 'Full-Stack Sui Starter on Steroids'
export const SITE_URL = 'https://sui-dapp-starter.dev'
export const GITHUB_PROJECT_NAME = 'sui-dapp-starter'
export const GITHUB_PROJECT_USER = 'kkomelin'
export const DISCORD_INVITE_LINK = 'https://discord.com/invite/HuDPpXz4Hx'
export const DEMO_URL = 'https://demo.sui-dapp-starter.dev'
